### PR TITLE
updates for zig 0.13.0

### PR DESCRIPTION
**Pull request by sethvincent**
Hi! This is just a few updates for zig 0.13.0: mostly build.zig api changes and small var -> const edits to make the compiler happy.

The main work was dealing with the absence of std.meta.trait in recent versions. I think the solution I landed on is alright; build/tests/example pass. I'm happy to make changes if needed!

### CODE REVIEW

**Comment by jwhear** [comment]
Seth, thanks for the submission.  Are you testing this with vanilla 0.13.0?  On my machine, this PR requires adding linking of libC and produces a bunch of errors around inlined functions that use `evex512` features--presumably a target selection issue or zig compiler issue; I haven't dug into it yet.

**Comment by sethvincent** [comment]
Oh strange! Yeah 0.13.0 installed with homebrew on macos.

**Comment by jwhear** [comment]
Looks like a bug in LLVM that was fixed here: https://github.com/llvm/llvm-project/issues/91719 but not before making it into Zig 0.13.0.
Whether it triggers depends on the build machine if using default target.

I'm going to add a big warning in the README and then merge this.

**Comment by sethvincent** [comment]
Dang, I didn't expect the issue to go as deep as llvm.

Thanks!

**Pull request merged**
